services:
  api:
    build: .
    container_name: nest_api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'rm -rf node_modules && npm install && npm run start:dev'
    environment:
      - NODE_ENV=development
